//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetBibliotheque
{
    using System;
    using System.Collections.Generic;
    
    public partial class bibliothecaire
    {
        public int bibliothecaire_ID { get; set; }
        public string bibliothecaire_login { get; set; }
        public string bibliothecaire_password { get; set; }
        public string bibliothecaire_nom { get; set; }
        public string bibliothecaire_prenom { get; set; }
    }
}
