//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetBibliotheque
{
    using System;
    using System.Collections.Generic;
    
    public partial class emprunter
    {
        public int livre_ID { get; set; }
        public int adherent_ID { get; set; }
        public Nullable<System.DateTime> date_emprunt { get; set; }
        public Nullable<System.DateTime> date_retour { get; set; }
    
        public virtual adherent adherent { get; set; }
        public virtual livre livre { get; set; }
    }
}
