//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetBibliotheque
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BibliothequeEntities : DbContext
    {
        public BibliothequeEntities()
            : base("name=BibliothequeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<adherent> adherents { get; set; }
        public virtual DbSet<auteur> auteurs { get; set; }
        public virtual DbSet<bibliothecaire> bibliothecaires { get; set; }
        public virtual DbSet<emplacement> emplacements { get; set; }
        public virtual DbSet<emprunter> emprunters { get; set; }
        public virtual DbSet<genre> genres { get; set; }
        public virtual DbSet<livre> livres { get; set; }
    }
}
